# Generated by Django 2.0.2 on 2018-03-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('location_area_encounters', models.CharField(max_length=200)),
            ],
        ),
    ]
